project_id = "mlbcbxajwzeocrmijqqf"

[functions.check-admin-exists]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.ebd-devotional]
verify_jwt = false

[functions.kids-daily]
verify_jwt = false

[functions.banner-image]
verify_jwt = true
